name: Build Image For Testing
description: Common docker image builder for building chainlink test images
inputs:
  chart_path:
    required: true
    description: The chart path to where the dockerfile is
  build_args:
    required: false
    description: The docker build args, if any
  push_tag:
    required: true
    description: The full docker tag to use for the push to ecr
  QA_AWS_ROLE_TO_ASSUME:
    required: true
    description: The AWS role to assume

runs:
  using: composite
  steps:
    - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721 # v2.10.2
      id: changes
      with:
        filters: |
          src:
            - '${{ inputs.chart_path }}/**'
    - name: Configure AWS Credentials
      if: steps.changes.outputs.src == 'false'
      run: echo "Nothing to push since changes don't affect this chart"
      shell: bash
    - name: Configure AWS Credentials
      if: steps.changes.outputs.src == 'true'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1 # public is always us-east-1
        role-to-assume: ${{ inputs.QA_AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 3600
    - name: Login to Amazon ECR
      if: steps.changes.outputs.src == 'true'
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public
    - name: Set up Docker Buildx
      if: steps.changes.outputs.src == 'true'
      uses: docker/setup-buildx-action@v1
    - name: Build and Push
      if: steps.changes.outputs.src == 'true'
      uses: docker/build-push-action@v3
      with:
        context: ./${{ inputs.chart_path }}
        file: ./${{ inputs.chart_path }}/Dockerfile
        # comma separated like: KEY1=VAL1,KEY2=VAL2,...
        build-args: ${{ inputs.build_args }}
        tags: ${{ inputs.push_tag }}
        push: true
