groups:
  - name: Keeper Alerts
    rules:
      - alert: Upkeep not performed
        expr: atlas_evm_exporter_upkeep_eligible_time_in_ms >= on (network_name, instance) group_left () atlas_evm_exporter_upkeep_eligible_time_alerting_threshold_in_ms
        for: 2m
        labels:
          severity: critical
          testnet_priority: true
          team: incident-response
        annotations:
          summary:
            "[{{ $labels.network_name }}] Upkeep ID {{ $labels.upkeep_id }} on registry {{ $labels.registry_address }} has been eligible for upkeep for {{ $value }} milliseconds with no upkeep performed"
          description: |
            Issue: Upkeep has been eligible for {{ $value }} milliseconds with no upkeep performed. 
            Keeper dashboard: https://chainlinklabs.grafana.net/d/o5cbnelGk/atlas-keeper-dashboard?orgId=1&var-network={{ $labels.network_name }}&var-registry_address={{ $labels.registry_address }} 

      - alert: Active Upkeeps near Limit
        expr: upkeeps_active_count >= on (network_name) group_left () upkeeps_active_count_alerting_threshold
        for: 2m
        labels:
          severity: warn
          team: keepers
        annotations:
          summary:
            "[{{ $labels.network_name | toUpper }}] Active Upkeep Count on registry {{ $labels.registry_address }} is nearing limit"
          description: |
            Issue: [Not Urgent] Active Upkeep count is getting near the limit.
            Keeper dashboard: https://chainlinklabs.grafana.net/d/o5cbnelGk/atlas-keeper-dashboard?orgId=1&var-network={{ $labels.network_name }}&var-registry_address={{ $labels.registry_address }}

      - alert: Eligible Upkeeps Count High
        expr: upkeeps_eligible_count >= on (network_name) group_left () upkeeps_eligible_count_alerting_threshold
        for: 2m
        labels:
          severity: warn
          team: keepers
        annotations:
          summary:
            "[{{ $labels.network_name | toUpper }}] Eligible Upkeep Count on registry {{ $labels.registry_address }} is higher than expected"
          description: |
            Issue: [Not Urgent] Eligible Upkeep count high.
            Keeper dashboard: https://chainlinklabs.grafana.net/d/o5cbnelGk/atlas-keeper-dashboard?orgId=1&var-network={{ $labels.network_name }}&var-registry_address={{ $labels.registry_address }}

      - alert: Node Last Perform Too Far From Current Block
        expr: keeper_last_perform_block < on(network_name) group_left () atlas_evm_exporter_block_heads - on(network_name) group_left () keeper_last_perform_block_alerting_threshold
        for: 2m
        labels:
          severity: warn
          team: keepers
        annotations:
          summary:
            "[{{ $labels.network_name | toUpper }}] Keeper Node {{ $labels.keeper_address }} on registry {{ $labels.registry_address }} has not done a perform recently."
          description: |
            Issue: A Keeper node has not done a perform since block {{ $value }}.
            Keeper dashboard: https://chainlinklabs.grafana.net/d/o5cbnelGk/atlas-keeper-dashboard?orgId=1&var-network={{ $labels.network_name }}&var-registry_address={{ $labels.registry_address }}
