groups:
  - name: VRF V2 BHS Stores
    rules:
      # Fire an alert if slowest distance between a VRF request and corresponding BHS store or
      # fulfillment is >= 60 blocks.
      - alert: SlowBHSStores
        labels:
          product: vrfv2
          severity: critical
          team: incident-response
        expr: vrfv2_slowest_bhs_store{network_name!~"polygon.*"} >= 60
        annotations:
          summary: '[{{ $labels.network_name | toUpper }}] [VRFv2] A randomness request has not been 
          fulfilled or had its blockhash stored for {{ $value }} blocks.'
          description: '[{{ $labels.network_name | toUpper }}] [VRFv2] The largest distance between a VRF
          request and the minimum of (fulfillment, blockhash stored, current block) is {{ $value }}
          blocks. This most likely means there is an issue with the BlockhashStore feeder.
          You can view VRF requests and BlockhashStores here: https://grafana.mgnt.devnet.tools/d/VPcEd3bnk/vrf-v2-and-bhs?orgId=1'

      - alert: SlowBHSStores (Matic)
        labels:
          product: vrfv2
          severity: critical
          team: incident-response
        expr: vrfv2_slowest_bhs_store{network_name=~"polygon.*"} > 256
        annotations:
          summary: '[{{ $labels.network_name | toUpper }}] [VRFv2] A randomness request has not been 
          fulfilled or had its blockhash stored for {{ $value }} blocks.'
          description: '[{{ $labels.network_name | toUpper }}] [VRFv2] The largest distance between a VRF
          request and the minimum of (fulfillment, blockhash stored, current block) is {{ $value }}
          blocks. This most likely means there is an issue with the BlockhashStore feeder.
          You can view VRF requests and BlockhashStores here: https://grafana.mgnt.devnet.tools/d/VPcEd3bnk/vrf-v2-and-bhs?orgId=1'

