groups:
  - name: Verified Random Function V2 Rules
    rules:
      - alert: SlowVRFv2Fulfillment
        labels:
          product: vrfv2
          severity: critical
          team: incident-response
        expr: vrfv2_oldest_unfulfilled_request_age >= on (network_name, instance) group_left () vrfv2_slow_request_age_threshold
        for: 2m
        annotations:
          summary: '[{{ $labels.network_name | toUpper }}] [VRFv2] A randomness request ({{ $labels.contract_address }}) with
            keyhash "{{ $labels.key_hash }}" has not been fulfilled for {{ $value }} blocks.'
          description: '[{{ $labels.network_name | toUpper }}] [VRFv2] A randomness request ({{ $labels.contract_address }}) with
            keyhash "{{ $labels.key_hash }}" has not been fulfilled for {{ $value }} blocks. You can view VRFv2 requests
            here: https://chainlinklabs.grafana.net/d/LWYaFW57k/atlas-vrfv2?var-network={{ $labels.network_name }}&var-fee_coin={{ $labels.fee_coin }}, be sure to use the appropriate fee coin for
            the blockchain (ETH, BNB, MATIC et al)'

      - alert: StalledVRFv2Fulfillment
        labels:
          product: vrfv2
          severity: critical
          team: incident-response
          testnet_priority: true
        expr: vrfv2_oldest_unfulfilled_request_age >= on (network_name, instance) group_left () vrfv2_stalled_request_age_threshold
        for: 2m
        annotations:
          summary: '[{{ $labels.network_name | toUpper }}] [VRFv2] A randomness request for
            "{{ $labels.key_hash }}" ({{ $labels.contract_address }}) has
            stalled, there has not been a fullfilment for {{ $value }} blocks.'
          description: '[{{ $labels.network_name | toUpper }}] [VRFv2] A randomness request for "{{ $labels.key_hash }}"
            ({{ $labels.contract_address }}) has stalled, there has not been a fullfilment for {{ $value }} blocks. You
            can view VRFv2 requests here: https://chainlinklabs.grafana.net/d/LWYaFW57k/atlas-vrfv2?var-network={{ $labels.network_name }}&var-fee_coin={{ $labels.fee_coin }},
            be sure to use the appropriate fee coin for the blockchain (ETH, BNB, MATIC et al)'

      - alert: NoFastVRFv2Fulfillments
        labels:
          product: vrfv2
          severity: critical
          team: incident-response
        expr: vrfv2_min_fulfill_delay >= on (network_name, instance) group_left () vrfv2_min_fulfill_delay_threshold
        for: 2m
        annotations:
          summary: '[{{ $labels.network_name | toUpper }}] [VRFv2] All randomness requests for keyhash {{ $labels.key_hash }}
            are fulfilling slowly. The fastest recent fulfillment occurred after {{ $value }} blocks.'
          description: '[{{ $labels.network_name | toUpper }}] [VRFv2] All randomness requests for keyhash 
            {{ $labels.key_hash }} are fulfilling slowly. The fastest recent fulfillment occurred after {{ $value }}
            blocks. This could indicate that the primary node is misconfigured, and only the backup is fulfilling 
            requests. You can view VRFv2 requests here: https://chainlinklabs.grafana.net/d/LWYaFW57k/atlas-vrfv2?var-network={{ $labels.network_name }},
            be sure to use the appropriate fee coin for the blockchain (ETH, BNB, MATIC et al)'
