{{- $fullName := include "mercury-server.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- if .Values.ingress.private.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-private" $fullName }}
  labels:
    {{- include "mercury-server.labels" . | nindent 4 }}
    mode: private
  {{- with .Values.ingress.private.annotations }}
  annotations:
    alb.ingress.kubernetes.io/actions.default-rule: >-
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"403","messageBody":"Forbidden"}}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.private.className }}
  defaultBackend:
    service:
      name: default-rule
      port:
        name: use-annotation
  rules:
  - host: "{{ .Values.ingress.private.domain }}"
    http:
      paths:
      {{- range $path := .Values.ingress.private.allowedPaths }}
      - path: {{ $path }}
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $servicePort }}
      {{- end }}
{{- end }}
{{- if .Values.ingress.public.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-public" $fullName }}
  labels:
    {{- include "mercury-server.labels" . | nindent 4 }}
    mode: public
  {{- with .Values.ingress.public.annotations }}
  annotations:
    alb.ingress.kubernetes.io/actions.default-rule: >-
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"403","messageBody":"Forbidden"}}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.public.className }}
  defaultBackend:
    service:
      name: default-rule
      port:
        name: use-annotation
  rules:
  - host: "{{ .Values.ingress.public.domain }}"
    http:
      paths:
      {{- range $path := .Values.ingress.public.allowedPaths }}
      - path: {{ $path }}
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $servicePort }}
      {{- end }}
{{- end }}
