apiVersion: v1
kind: Pod
metadata:
  name: remote-test-runner
spec:
  restartPolicy: Never
  volumes:
    - name: configmap-volume
      configMap:
        name: remote-test-runner-cm
  containers:
    - name: remote-test-runner
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      command: ["sh", "/root/init.sh"]
      volumeMounts:
        - name : configmap-volume
          mountPath: /root/test-env.json
          subPath: test-env.json
        - name : configmap-volume
          mountPath: /root/init.sh
          subPath: init.sh
      ports:
        - name: access
          containerPort: {{ .Values.remote_test_runner.access_port }}
      env:
{{- range $key, $value := .Values.remote_test_runner }}
  {{- if $value }}
        - name: {{ $key | upper}}
          value: {{ $value | quote}}
  {{- end }}
{{- end }}
{{- range $key, $value := .Values.remote_test_runner.secrets }}
  {{- if $value }}
        - name: {{ $key | upper}}
          valueFrom:
            secretKeyRef:
              name: remote-runner-secrets
              key: {{ $key | upper}}
  {{- end }}
{{- end }}
      resources:
        requests:
          memory: {{ .Values.resources.requests.memory }}
          cpu: {{ .Values.resources.requests.cpu }}
        limits:
          memory: {{ .Values.resources.limits.memory }}
          cpu: {{ .Values.resources.limits.cpu }}
{{- with .Values.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
  affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
  tolerations:
{{ toYaml . | indent 8 }}
{{- end }}