on:
  push:
    branches:
      - 'main'
name: Build Polygon Edge Image
jobs:
  build-image:
    environment: integration
    permissions:
      id-token: write
      contents: read
    name: Build Polygon Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Build Image
        uses: ./.github/actions/build-images
        env:
          repo: public.ecr.aws/chainlink/qa-polygon-edge
        with:
          chart_path: charts/polygon-supernet
          push_tag: ${{ env.repo }}:latest,${{ env.repo }}:${{ github.sha }}
          QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
