name: CI
on: pull_request

jobs:
  prettier:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@94e0aab03ca135d11a35e5bfc14e6746dc56e7e9 # pin@master
      - name: Run Prettier
        uses: creyD/prettier_action@394fa2de3b2acce9f63808b958c54aa823a43b71 # pin@v3.1
        with:
          dry: true
          prettier_options: --write **/*.{yaml,yml,json} --config ./.prettierrc.yaml --ignore-path ./.prettierignore
  helmlint:
    name: Lint Helm Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          # Without this parameter, the merged commit that CI produces will make it so that ct will
          # not detect a diff even if one exists
          fetch-depth: 0
      - name: Set up chart-testing
        uses: helm/chart-testing-action@b0d4458c71155b54fcf33e11dd465dc923550009 # pin@v2.0.1
      - name: Run chart-testing (lint)
        run: ct lint --config ${{ github.workspace }}/.github/workflows/configs/ct.yaml
  lint_workflows:
    name: Validate Github Action Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Collect Metrics
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@v1
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: Validate Github Action Workflows
        continue-on-error: true
      - name: Check out Code
        uses: actions/checkout@v3
      - name: Run actionlint
        uses: reviewdog/action-actionlint@c5d7b203340dfcb0f18fdf2ea44b0c10a1dee012 # v1.33.0
