name: CI
on: pull_request

jobs:
  prettier:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@94e0aab03ca135d11a35e5bfc14e6746dc56e7e9 # pin@master
      - name: Run Prettier
        uses: creyD/prettier_action@394fa2de3b2acce9f63808b958c54aa823a43b71 # pin@v3.1
        with:
          dry: true
          prettier_options: --write **/*.{yaml,yml,json} --config ./.prettierrc.yaml --ignore-path ./.prettierignore
  helmlint:
    name: Lint Helm Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
        with:
          # Without this parameter, the merged commit that CI produces will make it so that ct will
          # not detect a diff even if one exists
          fetch-depth: 0
      - name: Set up chart-testing
        uses: helm/chart-testing-action@b0d4458c71155b54fcf33e11dd465dc923550009 # pin@v2.0.1
      - name: Run chart-testing (lint)
        run: ct lint --config ${{ github.workspace }}/.github/workflows/configs/ct.yaml
